import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Navbar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";

const geistSans = localFont({
	src: "../lib/fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../lib/fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
	return (
		<html lang="en">
			<body className={`bg-neutral-950 ${geistSans.variable} ${geistMono.variable} antialiased`} >
				<Sidebar />
				<main className="main relative w-full md:w-[calc(100vw_-_24rem)] h-svh md:left-96">
					<Navbar />
					<div className="main-content h-[calc(100vh_-_7rem)]">
						{children}
					</div>
					<Footer />
				</main>
			</body>
		</html>
	);
}

export default RootLayout
